version: '3.8'

services:
  app:
    command: npm run dev
    volumes:
      # - ./app:/usr/src/app
      - ./app/pages:/usr/src/app/pages
      - ./app/public:/usr/src/app/public
      - ./app/styles:/usr/src/app/styles
      - ./app/libs:/usr/src/app/libs
      - ./app/components:/usr/src/app/components
      - ./app/server:/usr/src/app/server
      - ./app/client:/usr/src/app/client
  
