version: '3.8'

services:

  coturn:
    image: coturn/coturn:4.5.2-r5-debian
    command:
      - "--verbose"
      # - "--Verbose"
      - "--log-file=stdout"
      - "--listening-ip=0.0.0.0"
      - "--relay-ip=0.0.0.0"
      - "--external-ip=$$(detect-external-ip)"
      - "--min-port=49160"
      - "--max-port=49200"
      - "--lt-cred-mech"
      - "--realm kao2kao"
      - "--user ${TURN_SERVER_USER}:${TURN_SERVER_PASSWORD}"
    restart: always
    ports:
      - "3478:3478/tcp"
      - "3478:3478/udp"
      # - "49152-65535:49152-65535/udp"
      - "49160-49200:49160-49200/udp"
    volumes:
      - coturn_coturn:/var/lib/coturn
  app:
    build: ./app
    restart: always
    environment:
      - TURN_SERVER_URI=${TURN_SERVER_URI}
      - TURN_SERVER_USER=${TURN_SERVER_USER}
      - TURN_SERVER_PASSWORD=${TURN_SERVER_PASSWORD}
    ports:
      - 3000:3000
    depends_on:
      - coturn
  
volumes:
  coturn_coturn: