version: '3.8'

services:

  coturn:
    image: coturn/coturn:4.5.2-r5-debian
    command:
      - "--log-file=stdout"
      - "--external-ip=$$(detect-external-ip)"
      - "--min-port=49160"
      - "--max-port=49200"
    restart: always
    ports:
      - "3478:3478/tcp"
      - "3478:3478/udp"
      # - "49152-65535:49152-65535/udp"
      - "49160-49200:49160-49200/udp"
    volumes:
      - coturn_coturn:/var/lib/coturn
  app:
    build: ./app
    restart: always
    environment:
      - STUN_SERVER_URI=${STUN_SERVER_URI}
    ports:
      - 3000:3000
    depends_on:
      - coturn
  
volumes:
  coturn_coturn: