import Head from 'next/head'
import { useRef ,useState} from 'react';
import { useMount,useUnmount } from "react-use";
import MainClientApp from '../client/MainClientApp';
import RemoteVideo from '../components/RemoteVideo';
// import getConfig from "next/config";
// const { publicRuntimeConfig } = getConfig();


export default function Home({iceServers}) {
  const clientAppRef=useRef(null);
  const localVideoRef=useRef(null);
  const [remoteIsMuted,setRemoteIsMuted]=useState(true);

  useMount(async ()=>{
    const localVideo=localVideoRef.current;
    const clientApp=new MainClientApp({
      localVideo,
      iceServers,
    });
    window.clientApp=clientApp;
    clientAppRef.current=clientApp;
    await clientApp.setupPromise;
  });
  useUnmount(async ()=>{
    const clientApp=clientAppRef.current;
    await clientApp.destroyAsync();
  });
  const onClickJoin=()=>{
    const clientApp=clientAppRef.current;
    clientApp.onClickJoin();
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <label>remoteIsMuted <input type="checkbox" checked={remoteIsMuted} onChange={()=>setRemoteIsMuted(!remoteIsMuted)}/></label>
      <main>
      <video ref={localVideoRef} autoPlay playsInline muted />
      <button onClick={onClickJoin}>join</button>
      </main>

    </div>
  )
}

export async function getServerSideProps(context){
  const iceServers=[
    {
      urls: process.env.TURN_SERVER_URI,
      username:process.env.TURN_SERVER_USER,
      credential:process.env.TURN_SERVER_PASSWORD,
    },
  ];

  return {
    props:{
      iceServers,
    },
  };
}